### ISSUE TITLE
how use ? 

### ISSUE THREAD

**Issue by Gawaboumgaa** [pragmagic/godot-nim#50] opened 2019-12-08 17:41 UTC
Hi, I would like to use your binding but I have different problems
For example, I would just like to move a sprite on the screen but I don't see the code to do...
Could you make some examples in the repo? I tried to do it like in GdScript but I must be doing something wrong

**Comment by zetashift** [comment] 2019-12-09 20:24
Are you using https://github.com/pragmagic/godot-nim-stub ? It shows how to attach a NativeScript to a Node and how to use godot-nim.

**Comment by Skaruts** [comment] 2020-01-18 22:20
@zetashift I tried building _godot-nim-stub_ with nake, but it tells me `"Invalid GODOT_BIN path: C:\Users\Skaruts\Google Drive\Programming\Godot 3"` a million times until nake crashes.

I have no idea what can be causing that. I'm think about the fact the path contains spaces, and also that I have several versions of godot in the folder, where each executable is named differently, such as `Godot_v3.2-rc1_win64.exe`.

**Comment by zetashift** [comment] 2020-01-18 22:47
@Skaruts, yeah I was about to point out that it needs the executable path, glad nake is working now. Might be worth to check open up an issue either on nake or nim repo (if it uses the stdlib to work with paths) to make sure spaces are allowed.

As for your error `Failed to generate api.json`, I tried to reproduce but I'm not on Windows. With a clean install of godot / nake and using Godot RC1 I get a succesfull compile using latest Nim devel.
This is however on Linux x64. I'll have Windows access next week then I could check for you, but it should work.
Any more info about the error?

**Comment by Skaruts** [comment] 2020-01-18 23:25
@zetashift Well... the problem was that my project's folder also contained a space... :) It's all working now. Compiled nicely and the stub is running.

Thank you for testing it, or otherwise I would remain thinking the problem wasn't on my end and wouldn't have double checked.

**Comment by endragor** [comment] 2020-01-23 03:09
Closing as a duplicate of #17.

**Closed by endragor** 2020-01-23 03:09 UTC
